name: top_traded_300
market_proxy: SPY
cross_proxies:
- QQQ
- TLT
- UUP
- VIXY
universe:
- SPY
- TSLA
- NVDA
- AAPL
- MSFT
- AMZN
- AMD
- META
- GOOGL
- AVGO
- UNH
- NFLX
- LLY
- ORCL
- MU
- JPM
- INTC
- V
- CRM
- COST
- BAC
- XOM
- BA
- MA
- WMT
- GE
- CVX
- MRVL
- NOW
- ADBE
- GS
- JNJ
- CSCO
- HD
- PEP
- ASML
- C
- WFC
- TXN
- INTU
- AMAT
- PG
- QCOM
- IBM
- CAT
- TMO
- MRK
- KO
- BKNG
- MCD
- ANET
- LRCX
- TMUS
- ABBV
- NKE
- PFE
- PM
- DDOG
- ISRG
- DIS
- UNP
- KLAC
- SNPS
- LULU
- PGR
- T
- APH
- SBUX
- PDD
- ADI
- AXP
- ETN
- LMT
- MELI
- SCHW
- CMG
- VZ
- COF
- PYPL
- DHR
- NEE
- HON
- RTX
- GILD
- RCL
- MS
- BSX
- CMCSA
- NEM
- VRTX
- COP
- WDAY
- LOW
- CSX
- TJX
- UPS
- MDT
- TGT
- AMGN
- SHW
- DE
- BLK
- CME
- CCL
- SPGI
- DHI
- MCHP
- BMY
- FTNT
- CHTR
- NSC
- UAL
- NXPI
- CI
- SLB
- HWM
- STX
- REGN
- CDNS
- MCK
- MO
- HBAN
- JCI
- HCA
- ANSS
- MMM
- OXY
- MMC
- EBAY
- DAL
- CB
- WDC
- KR
- ADSK
- MDLZ
- HLT
- EQIX
- CVS
- USB
- BDX
- AXON
- ADP
- AON
- AMT
- AZO
- SYK
- 'ON'
- URI
- ZTS
- SO
- TEAM
- GM
- PH
- AJG
- ICE
- EA
- KEY
- WMB
- NRG
- ORLY
- EQT
- CL
- ROST
- MPWR
- EMR
- WELL
- KDP
- TTWO
- PWR
- NOC
- KHC
- HUM
- VLO
- TPR
- PLD
- MSI
- PNC
- KMI
- TER
- SNAP
- HPE
- EOG
- TWLO
- STZ
- WM
- DOW
- BK
- DLTR
- IT
- MAR
- MPC
- MNST
- EL
- ULTA
- CAH
- RF
- DUK
- ROP
- PSX
- PAYX
- MCO
- TEL
- LUV
- CTAS
- AEP
- ENPH
- IDXX
- NCLH
- TRV
- CCI
- ETSY
- CPRT
- HES
- IQV
- ECL
- TFC
- EW
- LYV
- JD
- GWW
- DG
- EXPE
- ALB
- OMC
- GLW
- O
- FANG
- DXCM
- ALL
- CTVA
- CMI
- RSG
- HAL
- GIS
- ROK
- D
- KMB
- TSCO
- HSY
- ODFL
- MOH
- VRSK
- NDAQ
- FAST
- YUM
- OKE
- CTSH
- SRE
- APD
- GDDY
- PCAR
- CF
- AFL
- ED
- RMD
- MRNA
- K
- DVN
- SPG
- EFX
- ZM
- VMC
- LYB
- EXC
- BBY
- PHM
- CSGP
- NUE
- ITW
- XEL
- MET
- AME
- WAT
- FIS
- CLX
- PSA
- SJM
- ALGN
- MLM
- LVS
- CBRE
- SYY
- VRSN
- SYF
- ETR
- IR
- AMP
- CAG
- VICI
- NTRS
- PEG
- WAB
- PPL
- HUBB
- PTC
- HPQ
- WYNN
- STT
- WEC
- FTV
- FITB
