name: top_traded_50
market_proxy: QQQ
cross_proxies:
- QQQ
- TLT
- UUP
- VIXY
universe:
- TSLA
- NVDA
- AAPL
- MSFT
- AMZN
- AMD
- META
- GOOGL
- AVGO
- UNH
- NFLX
- LLY
- ORCL
- MU
- JPM
- INTC
- V
- CRM
- COST
- BAC
- XOM
- BA
- MA
- WMT
- GE
- CVX
- MRVL
- NOW
- ADBE
- GS
- JNJ
- CSCO
- HD
- PEP
- ASML
- C
- WFC
- TXN
- INTU
- AMAT
- PG
- QCOM
- IBM
- CAT
- TMO
- MRK
- KO
- BKNG
- MCD
- ANET
